CREATE TABLE IF NOT EXISTS accommodations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    category            VARCHAR(255)                            NOT NULL,
    host_id             BIGINT                                  NOT NULL,
    num_rooms           INTEGER                                 NOT NULL,
    accommodation_state SMALLINT                                NOT NULL,
    CONSTRAINT pk_accommodations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS countries
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    continent VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hosts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,
    country_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_hosts PRIMARY KEY (id)
);

ALTER TABLE accommodations
    ADD CONSTRAINT uc_accommodations_name UNIQUE (name);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_name UNIQUE (name);

ALTER TABLE accommodations
    ADD CONSTRAINT FK_ACCOMMODATIONS_ON_HOST FOREIGN KEY (host_id) REFERENCES hosts (id);

ALTER TABLE hosts
    ADD CONSTRAINT FK_HOSTS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);



